"""Add user_id to jobs for isolation

Revision ID: 160e44b01ce6
Revises: 94e226f89bf0
Create Date: 2026-07-18 22:26:05.230257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '160e44b01ce6'
down_revision: Union[str, None] = '94e226f89bf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
