"""Drop custom auth fields for Supabase migration

Revision ID: 28b71c0c31d0
Revises: 45f7c1fe8b75
Create Date: 2026-07-18 21:36:59.405056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28b71c0c31d0'
down_revision: Union[str, None] = '45f7c1fe8b75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_constraint('users_firebase_uid_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'firebase_uid')
    op.drop_column('users', 'verification_otp')
    op.drop_column('users', 'color_failures')
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'color_sequence')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('color_sequence', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('otp_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('color_failures', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('verification_otp', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_firebase_uid_key', 'users', ['firebase_uid'], postgresql_nulls_not_distinct=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('device_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_2fa_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_sessions_pkey')
    )
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
