"""add_oauth_columns_to_user_email_configs

Revision ID: 3e9706e9cf16
Revises: a5f33g8h1i2j
Create Date: 2026-08-05 17:59:39.073518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e9706e9cf16'
down_revision: Union[str, None] = 'a5f33g8h1i2j'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_email_configs', sa.Column('oauth_access_token', sa.Text(), nullable=True))
    op.add_column('user_email_configs', sa.Column('oauth_refresh_token', sa.Text(), nullable=True))
    op.add_column('user_email_configs', sa.Column('oauth_token_uri', sa.String(length=512), nullable=True))
    op.add_column('user_email_configs', sa.Column('oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('user_email_configs', sa.Column('oauth_client_secret', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_email_configs', 'oauth_client_secret')
    op.drop_column('user_email_configs', 'oauth_client_id')
    op.drop_column('user_email_configs', 'oauth_token_uri')
    op.drop_column('user_email_configs', 'oauth_refresh_token')
    op.drop_column('user_email_configs', 'oauth_access_token')
    # ### end Alembic commands ###
